// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/protobuf/BattleProtocol.proto

package com.phoenix.protobuf;

public final class BattleProtocol {
  private BattleProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class BattleProto extends
      com.google.protobuf.GeneratedMessage {
    // Use BattleProto.newBuilder() to construct.
    private BattleProto() {
      initFields();
    }
    private BattleProto(boolean noInit) {}
    
    private static final BattleProto defaultInstance;
    public static BattleProto getDefaultInstance() {
      return defaultInstance;
    }
    
    public BattleProto getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.phoenix.protobuf.BattleProtocol.internal_static_myth_BattleProto_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.phoenix.protobuf.BattleProtocol.internal_static_myth_BattleProto_fieldAccessorTable;
    }
    
    // required uint32 messageField = 1;
    public static final int MESSAGEFIELD_FIELD_NUMBER = 1;
    private boolean hasMessageField;
    private int messageField_ = 0;
    public boolean hasMessageField() { return hasMessageField; }
    public int getMessageField() { return messageField_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasMessageField) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasMessageField()) {
        output.writeUInt32(1, getMessageField());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasMessageField()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, getMessageField());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.phoenix.protobuf.BattleProtocol.BattleProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.phoenix.protobuf.BattleProtocol.BattleProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.phoenix.protobuf.BattleProtocol.BattleProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.phoenix.protobuf.BattleProtocol.BattleProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.phoenix.protobuf.BattleProtocol.BattleProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.phoenix.protobuf.BattleProtocol.BattleProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.phoenix.protobuf.BattleProtocol.BattleProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.phoenix.protobuf.BattleProtocol.BattleProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.phoenix.protobuf.BattleProtocol.BattleProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.phoenix.protobuf.BattleProtocol.BattleProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.phoenix.protobuf.BattleProtocol.BattleProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.phoenix.protobuf.BattleProtocol.BattleProto result;
      
      // Construct using com.phoenix.protobuf.BattleProtocol.BattleProto.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.phoenix.protobuf.BattleProtocol.BattleProto();
        return builder;
      }
      
      protected com.phoenix.protobuf.BattleProtocol.BattleProto internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.phoenix.protobuf.BattleProtocol.BattleProto();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.phoenix.protobuf.BattleProtocol.BattleProto.getDescriptor();
      }
      
      public com.phoenix.protobuf.BattleProtocol.BattleProto getDefaultInstanceForType() {
        return com.phoenix.protobuf.BattleProtocol.BattleProto.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.phoenix.protobuf.BattleProtocol.BattleProto build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.phoenix.protobuf.BattleProtocol.BattleProto buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.phoenix.protobuf.BattleProtocol.BattleProto buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.phoenix.protobuf.BattleProtocol.BattleProto returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.phoenix.protobuf.BattleProtocol.BattleProto) {
          return mergeFrom((com.phoenix.protobuf.BattleProtocol.BattleProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.phoenix.protobuf.BattleProtocol.BattleProto other) {
        if (other == com.phoenix.protobuf.BattleProtocol.BattleProto.getDefaultInstance()) return this;
        if (other.hasMessageField()) {
          setMessageField(other.getMessageField());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setMessageField(input.readUInt32());
              break;
            }
          }
        }
      }
      
      
      // required uint32 messageField = 1;
      public boolean hasMessageField() {
        return result.hasMessageField();
      }
      public int getMessageField() {
        return result.getMessageField();
      }
      public Builder setMessageField(int value) {
        result.hasMessageField = true;
        result.messageField_ = value;
        return this;
      }
      public Builder clearMessageField() {
        result.hasMessageField = false;
        result.messageField_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:myth.BattleProto)
    }
    
    static {
      defaultInstance = new BattleProto(true);
      com.phoenix.protobuf.BattleProtocol.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:myth.BattleProto)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_myth_BattleProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_myth_BattleProto_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!src/protobuf/BattleProtocol.proto\022\004myt" +
      "h\032)src/protobuf/ExternalCommonProtocol.p" +
      "roto\"#\n\013BattleProto\022\024\n\014messageField\030\001 \002(" +
      "\rB\030\n\024com.phoenix.protobufH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_myth_BattleProto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_myth_BattleProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_myth_BattleProto_descriptor,
              new java.lang.String[] { "MessageField", },
              com.phoenix.protobuf.BattleProtocol.BattleProto.class,
              com.phoenix.protobuf.BattleProtocol.BattleProto.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.phoenix.protobuf.ExternalCommonProtocol.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
