//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ExternalCommonProtocol.proto
namespace myth
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"IntValueProto")]
  public partial class IntValueProto : global::ProtoBuf.IExtensible
  {
    public IntValueProto() {}
    
    private int _value;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int value
    {
      get { return _value; }
      set { _value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LongValueProto")]
  public partial class LongValueProto : global::ProtoBuf.IExtensible
  {
    public LongValueProto() {}
    
    private long _value;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long value
    {
      get { return _value; }
      set { _value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BoolValueProto")]
  public partial class BoolValueProto : global::ProtoBuf.IExtensible
  {
    public BoolValueProto() {}
    
    private bool _value;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool value
    {
      get { return _value; }
      set { _value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StringValueProto")]
  public partial class StringValueProto : global::ProtoBuf.IExtensible
  {
    public StringValueProto() {}
    
    private string _value;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string value
    {
      get { return _value; }
      set { _value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"IntStringProto")]
  public partial class IntStringProto : global::ProtoBuf.IExtensible
  {
    public IntStringProto() {}
    
    private int _intValue;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"intValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int intValue
    {
      get { return _intValue; }
      set { _intValue = value; }
    }
    private string _stringValue;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"stringValue", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string stringValue
    {
      get { return _stringValue; }
      set { _stringValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"IntValuesProto")]
  public partial class IntValuesProto : global::ProtoBuf.IExtensible
  {
    public IntValuesProto() {}
    
    private readonly global::System.Collections.Generic.List<int> _values = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"values", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> values
    {
      get { return _values; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"VariableValueProto")]
  public partial class VariableValueProto : global::ProtoBuf.IExtensible
  {
    public VariableValueProto() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private long _value;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long value
    {
      get { return _value; }
      set { _value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"VariableValuesProto")]
  public partial class VariableValuesProto : global::ProtoBuf.IExtensible
  {
    public VariableValuesProto() {}
    
    private readonly global::System.Collections.Generic.List<myth.VariableValueProto> _values = new global::System.Collections.Generic.List<myth.VariableValueProto>();
    [global::ProtoBuf.ProtoMember(1, Name=@"values", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<myth.VariableValueProto> values
    {
      get { return _values; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginProto")]
  public partial class LoginProto : global::ProtoBuf.IExtensible
  {
    public LoginProto() {}
    
    private string _loginSession;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"loginSession", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string loginSession
    {
      get { return _loginSession; }
      set { _loginSession = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CreateCharProto")]
  public partial class CreateCharProto : global::ProtoBuf.IExtensible
  {
    public CreateCharProto() {}
    

    private string _name = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }

    private int _job = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"job", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int job
    {
      get { return _job; }
      set { _job = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"MessageKey")]
    public enum MessageKey
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"S2C_REALTIME", Value=1)]
      S2C_REALTIME = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"S2C_LOGINERROR", Value=2)]
      S2C_LOGINERROR = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"S2C_NOCHARRET", Value=3)]
      S2C_NOCHARRET = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"S2C_CREATECHARERROR", Value=4)]
      S2C_CREATECHARERROR = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"S2C_ENTERGAMERET", Value=5)]
      S2C_ENTERGAMERET = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"C2S_LOGIN", Value=1001)]
      C2S_LOGIN = 1001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"C2S_CREATECHAR", Value=1002)]
      C2S_CREATECHAR = 1002
    }
  
}