//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: VipConfig.proto
namespace m
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"VipConfig")]
  public partial class VipConfig : global::ProtoBuf.IExtensible
  {
    public VipConfig() {}
    
    private int _Level;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Level
    {
      get { return _Level; }
      set { _Level = value; }
    }
    private int _Cosume;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Cosume", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Cosume
    {
      get { return _Cosume; }
      set { _Cosume = value; }
    }
    private string _desc;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"desc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string desc
    {
      get { return _desc; }
      set { _desc = value; }
    }
    private string _desc_en;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"desc_en", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string desc_en
    {
      get { return _desc_en; }
      set { _desc_en = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}